services:
  backend:
    build:
      context: ./backend
    container_name: flask_api
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
    environment:
      FLASK_APP: app.py
      FLASK_ENV: development

  frontend:
    build:
      context: ./frontend
    container_name: web_app
    ports:
      - "4321:4321"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend